export enum postTypes {
  FETCH_POSTS = 'FETCH_POSTS',
  CREATE_POST = 'CREATE_POST',
  UPDATE_POST = 'UPDATE_POST',
  DELETE_POST = 'DELETE_POST',
  UPVOTE_POST = 'UPVOTE_POST',
  FETCH_POST_BY_ID = 'FETCH_POST_BY_ID',
}
